### PR TITLE
support Ipv6 addresses

### PR DESCRIPTION
**Pull request by dominictarr**
closes https://github.com/ssbc/patchwork/issues/153#issuecomment-161967643

### CODE REVIEW

**Comment by dominictarr** [comment]
This should fix the issue, although clients will need to update their copy of ssb-ref to be able to connect to ipv6 peers.

**Comment by pfraze** [comment]
oh, so the issue was over-splitting on colons?

**Comment by pfraze** [comment]
:+1: to merge

**Comment by pfraze** [comment]
@dominictarr is this good to merge?

**Comment by dominictarr** [comment]
oh, oops, forgot about this.

**Comment by dominictarr** [comment]
merged into 2.2.2

**Pull request merged**
