### PR TITLE
add sigil prefixes

### PR DESCRIPTION
**Pull request by pfraze**
Adds sigil prefixes:

 - `@` for feeds
 - `%` for messages
 - `&` for blobs

Adds two new methods:

`isMsgId(str)`
`isBlobId(str)`

### CODE REVIEW

**Comment by pfraze** [comment]
added:
`isLinkId(str)` and 
`type(str)`

removed `isHash` and `isRef`

**Comment by dominictarr** [comment]
:+1:

**Comment by dominictarr** [comment]
merging

**Comment by dominictarr** [comment]
merged into 2.0.0

**Pull request merged**
