### PR TITLE
Support onion invites again

### PR DESCRIPTION
**Pull request by arj03**
Not sure when this broke, not everyday that I use it :) but people are interested in this and I have just checked that this makes invites work again (together with a minor patch in scuttlebot).

### CODE REVIEW

**Comment by arj03** [comment]
Unless anyone objects, I'll merge this soon, and add some documentation about tor.

Related:

https://github.com/ssbc/secret-stack/pull/18
https://github.com/ssbc/scuttlebot/pull/450

**Comment by dominictarr** [comment]
merged into 2.7.2 - sorry, my github notifications got really messy, but I got them tidied up so I should see things relatively quickly now.

**Comment by dominictarr** [comment]
oops, 2.8.1

**Comment by arj03** [comment]
Thanks. What about the two linked issues? One of them is on secret stack, where this one is also open? https://github.com/ssbc/secret-stack/pull/16

**Pull request merged**
