### PR TITLE
Compiled regex

### PR DESCRIPTION
**Pull request by mixmix**
hey @dominictarr just a small tweak : 
- extracts regex for slight perf advantage (?maybe?)
- exports regex for use elsewhere
- fix package.json repo location

### CODE REVIEW

**Comment by mixmix** [comment]
can you add me to npm so I can publish things in the future?

**Comment by dominictarr** [comment]
I'd be surprised if the v8 couldn't figure it out by itself.
but point 2 is good enough reason.

**Comment by dominictarr** [comment]
merged into 2.7.0, and you are also maintainer now

**Comment by mixmix** [comment]
thanks !

**Pull request merged**
